### ISSUE TITLE
Better model names

### ISSUE THREAD

**Issue by Gskartwii** [CrescentCode/Valkyrie_CI#6]
At the moment, model names look like "ValkyrieRBXL/ValkyrieFramework/bleeding-edge".  
Instead, ValkyrieRBXL model names should only have the branch name, and contributors' model names should not include the repository name. This information, along with info about the last commit should be included in the model's description.

**Comment by eLunate** [comment]
It should probably just be called "Valkyrie `branchname`" with all of the extra stuff in the description.

**Comment by Gskartwii** [comment]
I thought of just "branchname", but it may be confusing.

**Comment by Gskartwii** [comment]
Resolved by the referencing commits.
