### ISSUE TITLE
Built model's root Instance's name and type are not configurable

### ISSUE THREAD

**Issue by Gskartwii** [CrescentCode/Valkyrie_CI#9]
The root Instance will always be MainModule.mod.lua.

Moreover, you can only have on Instance in the root.

**Comment by eLunate** [comment]
It has to be MainModule, otherwise it can't be required by id; Roblox doesn't support `require(id)` on models where the root is not called MainModule

**Comment by Gskartwii** [comment]
I actually want this feature for when I'm creating plugins (which are run by Scripts) and places (where you need to have multiple Instances in the root)

**Comment by Gskartwii** [comment]
Resolved.
